services:
  - type: web
    name: hh-goa-identity-generator
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: RENDER
        value: "true"
